In [45]:
import numpy as np
import pandas as pd

In [46]:
df = pd.read_csv("ecommerce_sales.csv")

In [47]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [48]:
df.tail()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [49]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='str')

In [50]:
df.shape

(5000, 12)

In [51]:
df.dtypes

order_id              int64
order_date              str
customer_id           int64
product_category        str
region                  str
quantity              int64
unit_price          float64
discount            float64
payment_method          str
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 468.9 KB

In [55]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [56]:
df.head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
5,10006,1/6/2022,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10
6,10007,1/7/2022,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45
7,10008,1/8/2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01
8,10009,1/9/2022,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97
9,10010,1/10/2022,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39

In [57]:
df["product_category"].value_counts()

product_category
Electronics    1777
Clothing       1531
Home            969
Beauty          723
Name: count, dtype: int64

In [58]:
df["region"].value_counts()

region
West     1289
North    1276
East     1227
South    1208
Name: count, dtype: int64

In [59]:
df["order_date"]= pd.to_datetime(df["order_date"])

In [60]:
df["payment_method"].value_counts()

payment_method
Card      2270
COD       1774
Wallet     956
Name: count, dtype: int64

In [61]:
df.groupby("product_category")["revenue"].sum()

product_category
Beauty          765860.88
Clothing       1531931.72
Electronics    1829899.22
Home            982083.92
Name: revenue, dtype: float64

In [62]:
df.groupby("product_category")["revenue"].mean()

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [63]:
df.groupby("product_category")["revenue"].max()

product_category
Beauty         4005.93
Clothing       3928.63
Electronics    4119.33
Home           3640.56
Name: revenue, dtype: float64

In [64]:
df.groupby("product_category")["revenue"].min()

product_category
Beauty         20.94
Clothing       11.21
Electronics    13.26
Home           13.01
Name: revenue, dtype: float64

In [65]:
df["payment_method"].value_counts()

payment_method
Card      2270
COD       1774
Wallet     956
Name: count, dtype: int64

In [68]:
df.groupby("payment_method")["revenue"].agg(["sum" ,"mean"])

                       sum         mean
payment_method
COD             1788408.44  1008.122007
Card            2366248.20  1042.400088
Wallet           955119.10   999.078556

In [70]:
df["region"].value_counts()

region
West     1289
North    1276
East     1227
South    1208
Name: count, dtype: int64

In [71]:
df.groupby("region")["revenue"].agg(["sum","mean"])

               sum         mean
region
East    1236044.23  1007.371011
North   1281508.45  1004.316967
South   1246640.90  1031.987500
West    1345582.16  1043.896168

In [72]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [73]:
df.groupby("product_category")["revenue"].agg(["sum", "mean" , "min" , "max"])

                         sum         mean    min      max
product_category
Beauty             765860.88  1059.281992  20.94  4005.93
Clothing          1531931.72  1000.608570  11.21  3928.63
Electronics       1829899.22  1029.768835  13.26  4119.33
Home               982083.92  1013.502497  13.01  3640.56

In [74]:
df["product_category"].value_counts()

product_category
Electronics    1777
Clothing       1531
Home            969
Beauty          723
Name: count, dtype: int64

In [77]:
df["order_year"] = df["order_date"].dt.year

In [81]:
df["order_year"].value_counts()

order_year
2024    366
2028    366
2032    366
2022    365
2023    365
2025    365
2026    365
2027    365
2029    365
2030    365
2031    365
2033    365
2034    365
2035    252
Name: count, dtype: int64

In [80]:
df.groupby("order_year")["revenue"].agg(["sum"])

                  sum
order_year
2022        371824.30
2023        365915.79
2024        363209.13
2025        349802.33
2026        386369.69
2027        386151.91
2028        376844.80
2029        359239.24
2030        387884.46
2031        365250.83
2032        386584.63
2033        408725.72
2034        363239.55
2035        238733.36

In [86]:
working_df = df.copy()

In [103]:
working_df = df[df["order_year"] <= 2026]

In [104]:
working_df.shape

(1826, 13)

In [112]:
np.mean(working_df["revenue"])

np.float64(1006.0904928806135)

In [110]:
np.median(working_df["revenue"])

np.float64(783.5699999999999)

In [111]:
np.std(working_df["revenue"])

np.float64(821.8170609053799)

In [113]:
np.max(working_df["revenue"])

np.float64(4119.33)

In [ ]:
np.min(working_df["revenue"])

np.float64(12.83)

In [115]:
np.argmax(working_df["revenue"])

np.int64(809)

In [118]:
max_pos = np.argmax(working_df["revenue"])
working_df.iloc[max_pos]

order_id                          10810
order_date          2024-03-20 00:00:00
customer_id                        1890
product_category            Electronics
region                            South
quantity                              7
unit_price                       594.42
discount                           0.01
payment_method                     Card
delivery_days                         4
customer_rating                     4.9
revenue                         4119.33
order_year                         2024
Name: 809, dtype: object

In [120]:
min_pos = np.argmin(working_df["revenue"])
working_df.iloc[min_pos]

order_id                          10565
order_date          2023-07-19 00:00:00
customer_id                        1341
product_category               Clothing
region                            North
quantity                              1
unit_price                        19.74
discount                           0.35
payment_method                      COD
delivery_days                         8
customer_rating                     4.3
revenue                           12.83
order_year                         2023
Name: 564, dtype: object

In [122]:
np.max(working_df["revenue"]) - np.min(working_df["revenue"])

np.float64(4106.5)